title: iqrow
description: >- # this means to ignore newlines until "baseurl:"
  Matthew Harris (iqrow) blog
twitter_username: iqrow
github_username:  iqrow
permalink: /:title:output_ext

# Build settings
plugins:
  - jekyll-feed
